language: python
install:
- pip install -r main/requirements.txt
script:
- python -m pytest -v
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: priyanka.adivikolanu@gmail.com
  password:
    secure: jWjbc3vbM4ZCKgu2dYpKoqSK1P21j1F5/A0GfO9fu8p8WRGQtU849Qb3YfhhrxB+Jx4cov3JKEet6vOYdjlrT6i2Fp8AOo1ZvRhcW6K6OirDtyvuqjgUSr+AKH5PxeCcKnDxtNmd31PiodPJQlN5M0Z4c6gXnWAvfvuX7EwJo72jvuoCti/rL4Sm9lt6ngbsnr0WIfakn9Y0APEUoOpPytErKZCVHSidI6YgTF5A1Zes/crI/LV4XnamudvdpC+0i3y5+3bmXPyoYZxQQQZUsJ9p5/shzSDDnXw70qFHToFt/yMwPTdXR2bL/HdlDMN46vbsViF50KUasz5zabb5adN2XPdc25LCxEDIgs3roVsqubKDdyyK52nea3GuSJjQFr/i8ggi+nm2a6Z43vqgBzoW9vX0rX6l5lXNdCgIj1rABhsrumReoTrKmCLoVOdGtHYxymefflp0aIUgAbUMHtxJaOCZ0PX8d4NcCPTPIrmrrDskEzB7NGRths9jq690du+Q8xT7JR1lS8c4dvYp4Dq0kv4RgGqA86y2fudSiPH7FNgqHOKKnxAudYKPDFyyxJ+wTvOlpezoSru6BMp7Krdze5XAxMYYyYbQZqtxGRDpMYuQyHdV6ZzUlXpuMocYurSThVeLAYd75o/JG2ZHvlcxlmepmXRU+P0rAZHoLks=
  organization: priyanka-testing
  space: development
  manifest: main/manifest.yml
  on:
    repo: teja-priyanka/fibonacci-ci-cd
